### ISSUE TITLE
[Floppy][BUG] Notification Area Gets Spammed With Error Messages

### ISSUE THREAD

**Issue by yoruba-codigy** [manilarome/the-glorious-dotfiles#43] opened 2020-03-20 01:12 UTC
After More Than 20Hrs, I Installed Everything I Needed To Get Awesome WM Running And Install Your Theme. After A Few Minutes Of Use, I Noticed Some Errors Kept Popping Up Whenever I Hovered Over The Status Area (Wifi, Bluetooth, Music, e.tc) On The Top Right. Also, The Window Control Bar Always Seems To Get Hidden Under The Dock On The Left. Finally, Please How Do I Re-Map The Keyboard Shortcuts?

Cheers

Here's A Photo
![bug](https://user-images.githubusercontent.com/29712362/77128338-08747800-6a50-11ea-8c97-fe6a389e5ca1.png)

**Comment by manilarome** [comment] 2020-03-20 01:40
>  I Noticed Some Errors Kept Popping Up Whenever I Hovered Over The Status Area (Wifi, Bluetooth, Music, e.tc) On The Top Right

I can't reproduce it. Can I see your logs?

> The Window Control Bar Always Seems To Get Hidden Under The Dock On The Left.

It's not hiding under the dock. The titlebar will hide if there's only one client to save some screen space.

> How Do I Re-Map The Keyboard Shortcuts?

The keybinding for clients can be found in:

```
awesome/configuration/client/keys.lua
```

While the global key bindings are in:

```
awesome/configuration/keys/global.lua
```

**Comment by yoruba-codigy** [comment] 2020-03-20 04:23
Hi, Thank You, Here's AwesomeWM Logs:

[errors.log](https://github.com/manilarome/the-glorious-dotfiles/files/4357916/errors.log)

**Comment by manilarome** [comment] 2020-03-20 04:59
```
No window manager registered on screen 0. To start the xfdesktop without this check, run with --disable-wm-check.
2020-03-20 00:38:01 W: awesome: luaA_dofunction:78: error while running function!
stack traceback:
	[C]: in field 'field'
	/usr/local/share/lua/5.3/lgi/record.lua:118: in function </usr/local/share/lua/5.3/lgi/record.lua:92>
	(...tail calls...)
	[C]: in metamethod '__newindex'
	/usr/local/share/lua/5.3/lgi/record.lua:178: in function </usr/local/share/lua/5.3/lgi/record.lua:162>
	(...tail calls...)
	/usr/local/share/awesome/lib/awful/placement.lua:800: in upvalue 'fit_in_bounding'
	/usr/local/share/awesome/lib/awful/placement.lua:1794: in function </usr/local/share/awesome/lib/awful/placement.lua:1717>
	(...tail calls...)
	/usr/local/share/awesome/lib/awful/tooltip.lua:170: in upvalue 'apply_outside_mode'
	/usr/local/share/awesome/lib/awful/tooltip.lua:195: in upvalue 'set_geometry'
	/usr/local/share/awesome/lib/awful/tooltip.lua:215: in upvalue 'show'
	/usr/local/share/awesome/lib/awful/tooltip.lua:742: in local 'func'
	/usr/local/share/awesome/lib/gears/object.lua:152: in function 'widget.temperature.temperature-meter.emit_signal'
	/usr/local/share/awesome/lib/wibox/drawable.lua:329: in upvalue 'emit_difference'
	/usr/local/share/awesome/lib/wibox/drawable.lua:350: in upvalue 'handle_motion'
	/usr/local/share/awesome/lib/wibox/drawable.lua:443: in function </usr/local/share/awesome/lib/wibox/drawable.lua:443>
error: /usr/local/share/lua/5.3/lgi/record.lua:118: bad argument #3 to 'field' (number has no integer representation)
```

> No window manager registered on screen 0. To start the xfdesktop without this check, run with --disable-wm-check.

Are you using awesome with xfce/xfdesktop or something? I can't correlate the errors in the log to my setups.

**Comment by yoruba-codigy** [comment] 2020-03-20 05:00
Yes, I'm Using Awesome With xfce But xfcwm Is Disabled.

**Comment by manilarome** [comment] 2020-03-20 06:19
Can you try using the vanilla rc.lua or the gnawesome  setup? See if it still causing an error.

**Comment by yoruba-codigy** [comment] 2020-03-20 07:10
The Issue Still Persists With Gnawesome

**Comment by manilarome** [comment] 2020-03-20 07:14
How's the default rc.lua?

**Comment by yoruba-codigy** [comment] 2020-03-20 07:16
When Managed To Build Awesome From Source, There Was No ~/.config/awesome Folder, I Created It Manually

**Comment by manilarome** [comment] 2020-03-20 07:17
You copy a default one in `/etc/xdg/awesome/rc.lua`

**Comment by yoruba-codigy** [comment] 2020-03-20 07:20
That Directory Doesn't Exist On My PC

![Gitissue](https://user-images.githubusercontent.com/29712362/77143439-961d8b00-6a83-11ea-9f6b-d5f1b14b7cf0.png)

**Comment by manilarome** [comment] 2020-03-20 07:35
Oh. Okay try [this](https://github.com/awesomeWM/awesome/blob/master/awesomerc.lua) one

**Comment by manilarome** [comment] 2020-03-20 07:37
I have a question. Can you hover to the widget that have a tooltip? Then check if it causes the error. The widgets are the clock widget, the xdg-folders widget(trash, documents, home, etc.), task list and etc

**Comment by yoruba-codigy** [comment] 2020-03-20 07:38
Just Did, No Errors.

**Comment by yoruba-codigy** [comment] 2020-03-20 07:40
I Used The Awesomerc.lua file And No Errors Showed, I'll Try The Hovering Stuff Now.

**Comment by manilarome** [comment] 2020-03-20 07:41
> I Should Hover Over Tooltips For Your Dotfiles Right?

Yes :)

**Comment by yoruba-codigy** [comment] 2020-03-20 07:44
Hovering Over The Date, Bluetooth, Wifi And Trash Doesn't Trigger Anything, But Hovering Over The Home, Documents, Screen Record Widget, Music Widget Makes It Rain.

**Comment by manilarome** [comment] 2020-03-20 08:23
Can you try it on floppy?

**Comment by yoruba-codigy** [comment] 2020-03-20 08:32
Alright, Its Kinda Inverted

Doesn't Trigger On Home, Downloads, Documents, Trash And Wifi.
 Goes Loco On Music, (The Icon Before Screen Record), Bluetooth, Battery,

**Comment by manilarome** [comment] 2020-03-20 08:39
Can you change the `awful.tooltip{}` of the widgets of floppy that have an error with this:

```lua
awful.tooltip(
	{
		objects = {widget_button},
		mode = 'outside',
		align = 'right',
		text = 'Text',
		margin_leftright = dpi(8),
		margin_topbottom = dpi(8),    
		preferred_positions = {'right', 'left', 'top', 'bottom'}
	}
)
```

Check if it fixes the error.

**Comment by yoruba-codigy** [comment] 2020-03-20 08:54
Nah, It Doesn't..

I Modified The Music, Bluetooth And Battery Tooltip.

Music Displayed An Empty Tooltip Without Errors Twice, The Rest Are Not Having It.

**Comment by manilarome** [comment] 2020-03-20 09:02
Okay try the default rc.lua.

Just
```bash

$ rm -rf ~/.config/awesome

$ awesome-client 'awesome.restart()'
```

Then hover to the layout box. See if there's an error

**Comment by yoruba-codigy** [comment] 2020-03-20 09:15
Nope, No Errors, Hovered Over Every Possible Place.

**Comment by manilarome** [comment] 2020-03-20 09:25
I'm running out of ideas... I can't pinpoint the cause of the problem because I can't reproduce it here. Can you try again loading the floppy setup then comment all the tooltip of the widgets that causing an error? 

This is an important part of your log

```
	/usr/local/share/awesome/lib/awful/placement.lua:800: in upvalue 'fit_in_bounding'
	/usr/local/share/awesome/lib/awful/placement.lua:1794: in function </usr/local/share/awesome/lib/awful/placement.lua:1717>
	(...tail calls...)
	/usr/local/share/awesome/lib/awful/tooltip.lua:170: in upvalue 'apply_outside_mode'
	/usr/local/share/awesome/lib/awful/tooltip.lua:195: in upvalue 'set_geometry'
	/usr/local/share/awesome/lib/awful/tooltip.lua:215: in upvalue 'show'
	/usr/local/share/awesome/lib/awful/tooltip.lua:742: in local 'func'
	/usr/local/share/awesome/lib/gears/object.lua:152: in function 'widget.t
```

**Comment by yoruba-codigy** [comment] 2020-03-20 09:26
I'm Sorry For The Stress, I'll Try That Now.

**Comment by ildar** [comment] 2020-03-20 09:31
what's the awesomewm build's git hash?

**Comment by yoruba-codigy** [comment] 2020-03-20 09:33
Lemme Check

**Comment by manilarome** [comment] 2020-03-20 09:40
Oh. So you're just 2 commits behind.

**Comment by yoruba-codigy** [comment] 2020-03-20 09:42
I Built Awesome From Source Yesterday So That's Plausible.

**Comment by manilarome** [comment] 2020-03-20 10:06
Can you try again loading the floppy setup then comment all the tooltip of the widgets that causing an error?

**Comment by yoruba-codigy** [comment] 2020-03-20 10:25
Yeah, The Errors Are Gone But The Music Widget Kinda Depends On The Music Tooltip.

![giit](https://user-images.githubusercontent.com/29712362/77155160-6d09f400-6a9d-11ea-8ca1-bfa16a57abff.png)

**Comment by manilarome** [comment] 2020-03-20 10:36
> The Errors Are Gone

So it's the tooltip then? Can you please rebuild awesomewm-git from source? If you're using debian/debian-based distros please try this [method](https://gist.github.com/Bearbobs/2b744adda0a5151d4530ba763de993ef#file-awesome-configuration-L7-L12)

**Comment by yoruba-codigy** [comment] 2020-03-20 14:08
Sorry, Do You Happen To Know How To Uninstall The Present Built Version Of Awesome?

**Comment by manilarome** [comment] 2020-03-21 01:33
When I'm using the compiled version from source, I'm using this command
below to delete it. Make sure to check it first.

```bash
$ rm -rf /usr/local/share/doc/awesome /usr/local/share/awesome
/usr/local/bin/awesome*
```

**Comment by yoruba-codigy** [comment] 2020-03-21 21:13
Just Re-Installed Awesome, Errors Still Persist. I'll Just Silence The Notifications. I Modified My Port On Mpd, Where Do I Update It For The Music Widget?

**Comment by manilarome** [comment] 2020-03-22 01:21
Sorry I can't help you with the tooltip error problems, can't reproduce it. 

> Where Do I Update It For The Music Widget

In the `awesome/widget/music`

> What Version Of lgi Do You Use?

```
awesome v4.3-809-g5d1394b91 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: yes
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

**Comment by manilarome** [comment] 2020-03-29 07:31
I'll assume that you have already fixed it, so I'm closing this for now. Please reopen this again if I'm wrong.

**Closed by manilarome** 2020-03-29 07:31 UTC
Labels: bug
