### ISSUE TITLE
[GNawesOME] rewrite version problems

### ISSUE THREAD

**Issue by ildar** [manilarome/the-glorious-dotfiles#38] opened 2020-03-17 08:42 UTC
Thanks for getting the GNawesOME back.
The 1st couple of problems:
```
2020-03-17 14:16:43 E: awesome: Failed to load '/home/$USER/.config/awesome/widget/battery/icons/battery-charging.svg': Failed to open file “/home/ildar/.config/awesome/widget/battery/icons/battery-charging.svg”: No such file or directory
2020-03-17 14:20:43 E: awesome: Failed to load '/etc/xdg/awesome/widget/notif-center/icons/delete.svg': Failed to open file “/etc/xdg/awesome/widget/notif-center/icons/delete.svg”: No such file or directory
```

**Comment by manilarome** [comment] 2020-03-17 08:50
> 2020-03-17 14:16:43 E: awesome: Failed to load '/home/$USER/.config/awesome/widget/battery/icons/battery-charging.svg': Failed to open file “/home/ildar/.config/awesome/widget/battery/icons/battery-charging.svg”: No such file or directory

Uhm... I know about this. I broke the battery widget's logic when I rewrote it that's why it's causing that error in the log. I'll find a way to fix it. 

> 2020-03-17 14:20:43 E: awesome: Failed to load '/etc/xdg/awesome/widget/notif-center/icons/delete.svg': Failed to open file “/etc/xdg/awesome/widget/notif-center/icons/delete.svg”: No such file or directory

Uhm this is weird because I don't know why is awesome is in `/etc` directory lol. I'll try to investigate it.

**Comment by ildar** [comment] 2020-03-17 09:00
2nd, configuration/keys/global.lua doesn't seem to be launched.
E.g. modkey+F1 doesn't work, but modkey+s shows help.

**Comment by manilarome** [comment] 2020-03-17 09:06
> 2nd, configuration/keys/global.lua doesn't seem to be launched.
E.g. modkey+F1 doesn't work, but modkey+s shows help.

I can't reproduce this. I barely touch the `global.lua` while rewriting gnawesome so I'm sure. I didn't break anything there. Please, try logging in and out? Or rebooting?

**Comment by ildar** [comment] 2020-03-17 09:16
I do awesome.restart(). IMHO it should be more then enough.

The modkey+s looks coming from the default awesomwm rc.lua. I'll try to
build a newer awesomewm (mine is Feb 13 2020)
BTW did you add pcall/xpcall somewhere? I guess it's crashing silently in
one of those..

**Comment by manilarome** [comment] 2020-03-17 09:20
> BTW did you add pcall/xpcall somewhere? 

I only used it in the calculator widget but I did not implement it in gnawesome setup.

> build a newer awesomewm (mine is Feb 13 2020) 

Yeah you should. haha

**Comment by ildar** [comment] 2020-03-17 09:24
ok, doing that.
Meanwhile I found that in my setup require('layout') in rc.lua doesn't
return. It is weird.

**Comment by manilarome** [comment] 2020-03-17 09:26
The require('layout') creates the panels on all the screens. If you have panels, it's working.

**Comment by ildar** [comment] 2020-03-17 10:53
Allright, moving on.
```
  2020-03-17 16:50:36 E: awesome: Error during a protected call:
/usr/share/awesome/lib/gears/object/properties.lua:278: invalid object
stack traceback:
        [C]: in metamethod '__index'
        /usr/share/awesome/lib/gears/object/properties.lua:278: in function
</usr/share/awesome/lib/gears/object/properties.lua:277>
        [C]: in function 'xpcall'
        /usr/share/awesome/lib/gears/protected_call.lua:36: in function
</usr/share/awesome/lib/gears/protected_call.lua:35>
        (...tail calls...)
        /usr/share/awesome/lib/gears/timer.lua:245: in function
'gears.timer.run_delayed_calls_now'
```

**Comment by ildar** [comment] 2020-03-17 10:54
Also tray icons are too small, screenshot below.

**Comment by manilarome** [comment] 2020-03-17 11:30
>  in function 'xpcall'

I did not implemented the `xpcall`. And I can't trace the source of error based on that log.

> Also tray icons are too small

Can you change the value of base_size of system tray in `awesome/layout/bottom-panel.lua` to `dpi(20)` from `20`? Please report back. I think it's small for you because of the difference in our screen resolution.

**Comment by ildar** [comment] 2020-03-17 12:03
On Tue, Mar 17, 2020 at 5:30 PM Gerome Matilla wrote:

> in function 'xpcall'
>
> I did not implemented the xpcall. And I can't trace the source of error
> based on that log.
>
Yes, it's solved with awesomewm upgrade )))

> Also tray icons are too small
>
> Can you change the value of base_size of system tray in
> awesome/layout/bottom-panel.lua to dpi(20) from 20? Please report back. I
> think it's small for you because of the difference in our screen resolution.
>
perfectly helped, thanks a lot!

**Comment by manilarome** [comment] 2020-03-17 12:06
> Yes, it's solved with awesomewm upgrade )))

nice!

> perfectly helped, thanks a lot!

Okay, time to create a commit.

**Comment by ildar** [comment] 2020-03-17 12:08
also Modals covering everything is a very annoying feature.

**Comment by manilarome** [comment] 2020-03-17 12:13
What modals? You mean the center panel with notifications and calendar?

**Comment by ildar** [comment] 2020-03-17 14:52
Any application "Open" command starts File Chooser dialog. I mean that

**Comment by ildar** [comment] 2020-03-17 18:33
On Tue, Mar 17, 2020 at 6:08 PM Ildar wrote:

> also Modals covering everything is a very annoying feature.
>

found that: remove `draw_backdrop = true` from
configuration/client/rules.lua

**Comment by ildar** [comment] 2020-03-18 09:38
Didn't see you edited your comment )))

I almost finished tuning the new GNawesOME )) Besides `configuration/` I
did a little layout tuning,
https://github.com/ildar/the-glorious-dotfiles/commit/b04602c7b33413a19405449111317d84424f14cb

One thing I failed to win is `show_lockscreen()`. It doesn't accept the
right password. I'll look into it later.
Thanks a lot for your great work with this!

**Comment by manilarome** [comment] 2020-03-18 11:11
> I did a little layout tuning

Nice! :)

>  It doesn't accept the right password.

I discovered that sometimes if I'm typing my password, the color arc does not show. Confusing the user that the password has not been inputted. I'll investigate it tomorrow. Just try typing it carefully then validate. Don't rely on the color arc animation.

**Comment by manilarome** [comment] 2020-03-29 10:43
Hey, are you still having a problem with the rewrite version of `gnawesome`? Anyway, I already fixed the missing icon error in the logs produced by the battery widget. It also turns out that the `xpcall` error is also produced by the same battery widget. So it's fixed now, if I'm not mistaken.

**Closed** 2020-03-29 12:32 UTC
Labels: bug
