### ISSUE TITLE
Blur slider not taking effect

### ISSUE THREAD

**Issue by ibrahiemk** [manilarome/the-glorious-dotfiles#111] opened 2020-05-15 08:08 UTC
Full disclaimer: I'm fairly new to Linux and ricing :)
I'm running Kubuntu 20.04. I've struggled with installing various aspects of this, but I've worked through most of it. The issue I'm facing now is the blur slider and toggle don't seem to have any affect. I've enabled/disabled, moved the slider to min/max, and reloaded awesome. Any thoughts? TIA!

**Comment by manilarome** [comment] 2020-05-15 08:13
Uhmm are you using this [version](https://github.com/tryone144/picom/tree/feature/dual_kawase) of picom? And are you using a virtual machine?

**Comment by ibrahiemk** [comment] 2020-05-15 08:26
Yes I'm using that version (took me a while to build it right). And no it's a direct install. Only thing regarding the picom/compton build, it said libenv was missing during the build, but that dependency is installed and everything completed successfully. 
I feel like something is missing...Ark for example has transparent menu bars, but not main window. While kitty is fully transparent (with blur I mean).

**Comment by manilarome** [comment] 2020-05-15 08:31
Thanks for the info. Please, check if it's running. Run `pgrep picom`. If not, try to run it through terminal.

**Comment by ibrahiemk** [comment] 2020-05-15 08:41
Thank you for the awesome package and support :)
Yes, it's running. I'm getting blur (which I wasn't with the default compton install), it's just not adjustable.

**Comment by manilarome** [comment] 2020-05-15 08:44
Good! Then kill it by `killall picom` then press <kbd>super + x </kbd> to toggle picom on and off. The point of this is to use the picom config of the setup so it will listen to changes.

**Comment by ibrahiemk** [comment] 2020-05-15 09:06
Ok... I did that. Killing picom removes all transparency (expected). Adjusting the slider at that point doesn't do anything. super+x then gives about 20%? transparency. I suspect whatever the default is. [
![1589533476](https://user-images.githubusercontent.com/3018979/82032795-63e27100-9661-11ea-8a77-bebfa4f6bf13.png)
](url)

**Comment by manilarome** [comment] 2020-05-15 09:10
I see thanks for reporting this. Seems the code `grep -F 'strength =' ~/.config/awesome/configuration/picom.conf | awk 'NR==1 {printf $3}' | tr -d ';'` is not working with bash. I'm currently using zsh so that's why I can't reproduce this earlier. Will fix it now

**Comment by ibrahiemk** [comment] 2020-05-15 09:15
Thank you so much!! I'll also install zsh (was on my todo).

**Comment by manilarome** [comment] 2020-05-15 10:02
Done! https://github.com/manilarome/the-glorious-dotfiles/commit/44f944436248729a5b51cb46057868f013c6df67 Please report back if it's working in your end.

**Comment by ibrahiemk** [comment] 2020-05-15 22:15
Yep that worked! Thank you! Not sure if it's appropriate for me to close this.

**Comment by manilarome** [comment] 2020-05-15 22:51
Nice! Thanks for reporting back. :) Will close this now.

**Closed by manilarome** 2020-05-15 22:51 UTC
