### ISSUE TITLE
[BUG][Floppy] Music Widget don't work properly

### ISSUE THREAD

**Issue by Chaos4U** [manilarome/the-glorious-dotfiles#77] opened 2020-04-09 10:02 UTC
Hi,i wanted to play music) so all working but when i reboot my pc there is no music in widget,updating ncmpcpp not working only when i click play on all tracks.
Help me please =)

**Comment by manilarome** [comment] 2020-04-09 10:20
> when i reboot my pc there is no music in widget

It also happens to me sometimes. It should update if you press play. :)

**Comment by Chaos4U** [comment] 2020-04-09 10:59
> > when i reboot my pc there is no music in widget
> 
> It also happens to me sometimes. It should update if you press play. :)

i have 0/15 tracks ._.

**Comment by manilarome** [comment] 2020-04-09 11:09
> i have 0/15 tracks ._.

Is this an output of ncmpcpp? If you have 0/15, try adding tracks to your playlist. :) To add the track to playlist just play the song it will automatically add it to the playlist.

**Comment by ildar** [comment] 2020-04-09 11:12
what's the output of `mpc` ?

**Comment by Chaos4U** [comment] 2020-04-09 11:13
> > i have 0/15 tracks ._.
> 
> Is this an output of ncmpcpp? If you have 0/15, try adding tracks to your playlist. :) To add the track to playlist just play the song it will automatically add it to the playlist.

i think im doing this every time i reboot ._.

**Comment by manilarome** [comment] 2020-04-09 11:27
Follow ildar's suggestion, what is the output of the command `mpc`?

**Comment by Chaos4U** [comment] 2020-04-09 11:45
> Follow ildar's suggestion, what is the output of the command `mpc`?

volume: n/a   repeat: off   random: off   single: off   consume: off

**Comment by manilarome** [comment] 2020-04-09 11:56
Run `mpc play` then check the music widget. Then report back if it's still not working

**Comment by Chaos4U** [comment] 2020-04-09 12:11
> Run `mpc play` then check the music widget. Then report back if it's still not working

same

**Comment by manilarome** [comment] 2020-04-09 13:14
Still `volume: n/a repeat: off random: off single: off consume: off`? Maybe your mpd is not running or you don't have `mpd.db`. Try `mpc update`

**Comment by Chaos4U** [comment] 2020-04-10 04:57
> Still `volume: n/a repeat: off random: off single: off consume: off`? Maybe your mpd is not running or you don't have `mpd.db`. Try `mpc update`

same xD

**Comment by manilarome** [comment] 2020-04-10 05:20
I'm sorry but I really can't reproduce this. All the music widget need is `mpd`, `mpc`, some music files, and a running mpd server to run. Closing this now.

**Closed by manilarome** 2020-04-10 05:20 UTC
Labels: discussion

**Comment by Chaos4U** [comment] 2020-04-10 06:27
> I'm sorry but I really can't reproduce this. All the music widget need is `mpd`, `mpc`, some music files, and a running mpd server to run. Closing this now.

i Fixed it with small script in .xinitrc =) anyway thanks
