### ISSUE TITLE
[BUG] GNawesome dock corner not transparent

### ISSUE THREAD

**Issue by Tibo-le-canard** [manilarome/the-glorious-dotfiles#186] opened 2020-09-24 07:26 UTC
**Technical Information (please complete the following information):**
 - Setup: GNawesOME

**Describe the bug**
When using the blurry effect the corner of the dock is blurry and not transparent.

**Expected behavior**
It should be transparent.

**Screenshots**
![blurrycorner](https://user-images.githubusercontent.com/10544393/94113221-d69cfd80-fe46-11ea-8130-657308c76fc8.png)

**Patch**
I made a patch for that: [c723d62845983393aa34c89fccca796dfd71ad22](https://github.com/Tibo-le-canard/the-glorious-dotfiles/commit/c723d62845983393aa34c89fccca796dfd71ad22)
Here is the screenshot after the patch: 
![notblurrycorner](https://user-images.githubusercontent.com/10544393/94113779-b457af80-fe47-11ea-8a68-008750e8394b.png)
It should not break anything.

What about storing the shape somewhere in a configuration file ?
So it could be easily changed afterwards.

**Comment by manilarome** [comment] 2020-09-24 08:21
It is transparent and this is not a bug. This is expected due to the anti-alias hack I implemented. Notice that the dock in the second screenshot has rough edges, while the first one has a smooth corner (minus the blurred corner of course). But yeah, the anti-aliased corner hack is perfect if you're not using a blur filter. Closing this now! Thanks for reporting tho!

**Closed by manilarome** 2020-09-24 08:21 UTC
Labels: discussion, not a bug

**Comment by Tibo-le-canard** [comment] 2020-09-24 09:05
Oh ok I understand now :smile: !
I guess this why it is also the case with the topbar and notification corners.

What do you think of adding a boolean option inside a config file to disable/enable the anti-aliased trick ?
With a high resolution, aliased corner are less noticeable than the artifact.

**Comment by Tibo-le-canard** [comment] 2020-09-24 09:50
Or what about using Ibhagwan's picom fork ?

**Comment by manilarome** [comment] 2020-09-24 10:21
> What do you think of adding a boolean option inside a config file to disable/enable the anti-aliased trick ?

Sorry, but I don't really plan on changing/add it right now. My goal as of now is to maintain and improve the setups. So yeah, I'm not adding a feature or create a new awesomewm setup in the meantime. 

>  With a high resolution, aliased corner are less noticeable than the artifact it creates.

I haven't thought of that before! Maybe I'll remove the "hack" if I bought a high res monitor.

> Or what about using Ibhagwan's picom fork for beautiful corner :) ?

IIRC ibhagwan is not rebasing the upstream to his fork so yeah. Let's just wait with picom.

**Comment by Tibo-le-canard** [comment] 2020-09-24 11:55
> > What do you think of adding a boolean option inside a config file to disable/enable the anti-aliased trick ?
> 
> Sorry, but I don't really plan on changing/add it right now. My goal as of now is to maintain and improve the setups. So yeah, I'm not adding a feature or create a new awesomewm setup in the meantime.
> 
Oh but I'm willing to make the changes myself ! (And I see that as improvement for high res setup)
Will you accept a merge request ? Or are you just not interested ?

**Comment by manilarome** [comment] 2020-09-24 22:56
> Or are you just not interested?

This. I'm not really planning on changing anything right now. Thank you tho!
