### ISSUE TITLE
[FEATURE REQUEST][ALL] XDG Autostart Conformity

### ISSUE THREAD

**Issue by xieve** [manilarome/the-glorious-dotfiles#115] opened 2020-05-23 20:38 UTC
There's a simple snippet on the [ArchWiki page of AwesomeWM](https://wiki.archlinux.org/index.php/Awesome#Autostart) to implement the XDG autostart specification:
```Lua
   awful.spawn.with_shell(
       'if (xrdb -query | grep -q "^awesome\\.started:\\s*true$"); then exit; fi;' ..
       'xrdb -merge <<< "awesome.started:true";' ..
       -- list each of your autostart commands, followed by ; inside single quotes, followed by ..
       'dex --environment Awesome --autostart --search-paths "$XDG_CONFIG_DIRS/autostart:$XDG_CONFIG_HOME/autostart"' -- https://github.com/jceb/dex
       )
```
It allows for applications and users to conveniently add autostart applications in a standardized way, without meddling with the actual config files, e.g. I want to start KDE Connect whenever I launch Awesome.

**Comment by manilarome** [comment] 2020-05-29 02:02
Uhm what's the advantage of this compared to [auto-start module](https://github.com/manilarome/the-glorious-dotfiles/blob/master/config/awesome/floppy/module/auto-start.lua)? I'm just curious because the module works very well and pretty simple. The module also checks if the command is already running to avoid duplication.

**Comment by RMTT** [comment] 2020-06-08 09:34
> Uhm what's the advantage of this compared to [auto-start module](https://github.com/manilarome/the-glorious-dotfiles/blob/master/config/awesome/floppy/module/auto-start.lua)? I'm just curious because the module works very well and pretty simple. The module also checks if the command is already running to avoid duplication.

I thinks his means is that auto start the desktop file, not binary.

**Comment by manilarome** [comment] 2020-06-08 23:25
> I thinks his means is that auto start the desktop file, not binary.

Ohh. Yes, I think it's a nice addition

**Comment by manilarome** [comment] 2020-07-05 10:05
Hey so I created a script to read and execute the `.desktop` files in `$HOME/.config/autostart`. The snippet in the Archwiki needs `dex`, but I don't really want to add more dependency because the setups are too bloated right now. Here's the script and it's only tested in `bash`:

```bash
#!/usr/bin/env bash
for filename in $HOME/.config/autostart/*;
do
	$(grep '^Exec' $filename | tail -1 | sed 's/^Exec=//' | sed 's/%.//' | sed 's/^"//g' | sed 's/" *$//g') &
done
```

So yeah, it will iterate through all the files in autostart directory. The problem is, currently it doesn't check if it's a `.desktop` file and it also doesn't check if the program is already running so yeah the script needs more features like that. You can put it inside a `awful.spawn.easy_async_with_shell()`. Right now, I don't really have the time to add the missing features and converting this into a module so I'll just leave this here for now. Thank you!

**Comment by manilarome** [comment] 2020-09-17 07:46
Closing this now, because I'm really satisfied with the auto-start module and all the `.destop` files in my `~/.config/autostart` are running automatically without any tweak. So yeah, closing this now. Thanks!

**Closed by manilarome** 2020-09-17 07:46 UTC
Labels: discussion, feature request
