### ISSUE TITLE
[BUG & QUESTION][Linear] help for some modifications

### ISSUE THREAD

**Issue by Hkyx** [manilarome/the-glorious-dotfiles#91] opened 2020-04-15 19:57 UTC
Hi @manilarome, 

Me again ;) I'll put all my question in one, it''ll more easy like that.

### Notifications
First about the notifications, if If I receive chrome noitifications, the widget appear to be in red, if I receive slack notification, the ui is black with a oppacity. There it can be ok, but get the same ui for all the notifications can be cool. Where I got a bug is when I receive microsoft teams (yeahhh...), notifications. 
The notifications came on the screen and split up my actuel windows app like terminal, emacs or others by 50% and show the notifications windget just right of the app. 
Checked in the config bu I don't see where I can stick this notification to the top right without interractict with my focused windows

### Bottom Panel
I did some modification like widht, border, color, etc. but need some help for my last settings: 
- How to put a bottom border only ? already did that but it apply to all the bar.
- how to make the bar floating (in fact like this: https://camo.githubusercontent.com/b79a110ca8a04daa1285cb36dee056ac511e0ded/68747470733a2f2f692e696d6775722e636f6d2f357056335878612e706e67)

### Music Widget
I change the music widget to the right of my bottom_panel, but the mini-windows that show up when you clic, is still a left of the screen. I tried to manage the position in the configuration from x_position .... but doesn't change anything. I probably make a bad try but if you got a idea... :)

### Widgets: 
- Network: it seems, the widget in the bottom bar show that wifi is connected but can't find the network name: "Connected to: N/A"
- Bluetooth: the widget let the icon as bluetooth is active, some device is connected but: "bluetooth is off"

Thanks,

Hk

**Comment by manilarome** [comment] 2020-04-16 01:05
> If I receive chrome noitifications, the widget appear to be in red

This is an upstream or the application(google chrome)'s fault. Can reproduced this using the vanilla rc.lua

![error](https://user-images.githubusercontent.com/40349590/79402687-30a7b600-7fbf-11ea-93d6-e67b02ed547f.png)

>  Where I got a bug is when I receive microsoft teams (yeahhh...), notifications.
The notifications came on the screen and split up my actuel windows app like terminal, emacs or others by 50% and show the notifications windget just right of the app. 

I'm sorry, I can't test it for I don't have it installed. :grimacing: There's a reddit post [here](https://www.reddit.com/r/awesomewm/comments/g1yad3/use_microsoft_teams_preview_with_awesome_wm/). Please check the comments there.

> How to put a bottom border only ? already did that but it apply to all the bar.

You can't. Applying border in awesomewm means applying it on all sides.

> how to make the bar floating

In the linear setup, the bar is `awful.wibar`, so change it to `wibox` so you can set the `x` and `y`. Then, alter its `width`, height, `x`, and `y`.  More info [here](https://awesomewm.org/apidoc/popups_and_bars/wibox.html). 

You can also check my old [awesome dotfiles setup](https://www.reddit.com/r/unixporn/comments/dmvcev/awesome_rounded/) that has the `floating bar` effect. Relevant code [here](https://github.com/manilarome/old-awesome-dotfiles/blob/64cb0522c3d28862348054c2a0448549a8da5d88/rounded/layout/bottom-panel.lua#L82-L104)


> I change the music widget to the right of my bottom_panel, but the mini-windows that show up when you clic, is still a left of the screen

Change the `awful.placement.bottom_left` to `awful.placement.bottom_right`. 

> "Connected to: N/A"

Sometimes it happens when you don't have an unstable internet connection.

> Bluetooth: the widget let the icon as bluetooth is active, some device is connected but: "bluetooth is off"

I'll look into it.



As for the upstream bugs/application bugs(I can't say which of the two), I can't really help you with that, sorry. Please, consider reporting it to awesomewm devs. :)

**Comment by ildar** [comment] 2020-04-16 10:58
> I receive chrome noitifications, the widget appear to be in red, if I
receive slack notification, the ui is black with a oppacity. There it can
be ok, but get the same ui

This is the matter of `urgency`.
http://manpages.ubuntu.com/manpages/xenial/man1/notify-send.1.html

**Comment by manilarome** [comment] 2020-04-16 13:02
> This is the matter of `urgency`.

Yeah but the notifications should not be in critical level on google chrome. It works just fine on firefox.

**Comment by Hkyx** [comment] 2020-04-16 15:16
Hi, 

No problems for the bugs part, it's cool from to reply to my issue so ... :)
For the wibox, I tried like my last issue related to that and I don't know why but it still not displayed on the screen  without any error. 
it came with awesome and got the last build, so I don't really understand why it bug like that... 

I just try the elenapan manta's theme who got one too and it's working, I tried a wibox and disable widget one by one from linear, but it seems not related to that.

Tried the notification and it worked, 'll follow the reddit too.

**Comment by manilarome** [comment] 2020-04-17 01:10
> I tried like my last issue related to that and I don't know why but it still not displayed on the screen without any error.

I really should investigate about that because it works fine in my laptop. Can you tell me what screen resolution that you are using with linear? I'll try it on a vm. Thanks!

**Comment by Hkyx** [comment] 2020-04-17 01:53
I tried few resolution from 1920*1080 to 2560*1440

Resolution set with xrandr script.

But not sure the resolution is the problem if the elenapan manta's theme is
working for the wibox, just don't understand the difference between this
one and linear



Le jeu. 16 avr. 2020 21:10, Gerome Matilla <notifications@github.com> a
écrit :

**Comment by manilarome** [comment] 2020-04-17 02:02
Please try changing the bottom-panel's wibar to:

```lua
	local panel_height = dpi(48)

	local panel_y = (s.geometry.y + s.geometry.height) - panel_height

	local panel = wibox
	{
		ontop = true,
		screen = s,
		type = 'dock',
		height = dpi(panel_height),
		width = s.geometry.width,
		x = s.geometry.x,
		y = dpi(panel_y),
		bg = beautiful.background,
		fg = beautiful.fg_normal
	}
```

A resolution of 2560x1440 using the code above:

![nani](https://user-images.githubusercontent.com/40349590/79524149-56ea5600-8092-11ea-87bd-fbf2e4e64d68.png)

**Comment by Hkyx** [comment] 2020-04-17 13:25
Hi @manilarome , 

Thank you for the update, it's not working but not far: 
found the problem i think and it came from the y which is not working on my side. 
- If I comment it it's working and show it at the top. 
- if I put a manual value it's working
but the calcul method doesn't work, I try a math.floor and s.geometry.width but still not good a this points.

if you got a idea to manage the calcul which can work ? 
looking for something like (bottom - panel_height) - dpi(40) or something like that.

**Comment by manilarome** [comment] 2020-04-17 13:50
> it came from the y which is not working on my side.

Well `y`'s value will always be `0` unless you have a vertical multimonitor setup.

> If I comment it it's working and show it at the top.

Uhm yeah because that line adds the geometry height to y which is `0`. So: `(y(0) + s.geometry.height(your screenheight)) - panelheight(40)` will show the bottom panel at the bottom. This is the only reason we're using `wibox` instead of `awful.wibar`, because the latter is using `placement` to put the bar to screen edges and will not apply the "gaps".

Please this one:

```lua
	local panel_height = 48
	local panel_margin = 10
	local panel_y = s.geometry.height - panel_height

	local panel = wibox
	{
		ontop = true,
		screen = s,
		type = 'dock',
		height = dpi(panel_height),
		width = dpi(s.geometry.width - panel_margin),
		x = s.geometry.x + (panel_margin / 2),
		y = panel_y - (panel_margin / 2),
		bg = beautiful.background,
		fg = beautiful.fg_normal
	}
	

	panel:struts
	{
		bottom = panel_height + panel_margin
	}
```

![20200417_213556](https://user-images.githubusercontent.com/40349590/79575756-d27cef00-80f4-11ea-8266-34bf789fb4fa.png)

I'm sorry but I'm really running out of idea. Please just experiment with the `x` and `y`.

**Comment by Hkyx** [comment] 2020-04-17 13:58
And it's perfectly working .... 

big mistacke from myself, thinking about x and y values and start. so it make a bug sense... 

big thanks @manilarome  you're really awesome ;) :1st_place_medal:

**Comment by manilarome** [comment] 2020-04-17 14:01
Nice! Glad it worked! Thanks! Closing this now! :)

**Closed** 2020-04-17 14:02 UTC
Labels: question, upstream
