### ISSUE TITLE
[BUG][LINEAR] wibar not working 

### ISSUE THREAD

**Issue by Hkyx** [manilarome/the-glorious-dotfiles#70] opened 2020-04-06 20:39 UTC
Hi, 

I tried a fresh install on manjaro, I added the needed and optionnals dependencies, but it seems the wibar is not visible. the layout when I open a terminal or others app let the space of the wibar free so it's like she's there but not visible.

Any idea? 

regards,
Hk

**Comment by Hkyx** [comment] 2020-04-07 01:11
logs from reload:

```
Apr 06 21:09:15 lmp /usr/lib/gdm-x-session[39825]: 2020-04-06 21:09:15 W: awesome: xerror:1053: X error: request=GrabKey (major 33, minor 0), error=BadAccess (10)
Apr 06 21:09:15 lmp /usr/lib/gdm-x-session[39825]: 2020-04-06 21:09:15 W: awesome: xerror:1053: X error: request=GrabKey (major 33, minor 0), error=BadAccess (10)
Apr 06 21:09:15 lmp /usr/lib/gdm-x-session[39825]: 2020-04-06 21:09:15 W: awesome: xerror:1053: X error: request=GrabKey (major 33, minor 0), error=BadAccess (10)
Apr 06 21:09:15 lmp /usr/lib/gdm-x-session[39825]: 2020-04-06 21:09:15 W: awesome: xerror:1053: X error: request=GrabKey (major 33, minor 0), error=BadAccess (10)
Apr 06 21:09:16 lmp /usr/lib/gdm-x-session[39825]: 2020-04-06 21:09:16 E: awesome: Error during a protected call: /home/hk/.config/awesome/widget/weather/init.lua:258: bad argument #1 to 'gsub' (string expected, got nil)
Apr 06 21:09:16 lmp /usr/lib/gdm-x-session[39825]: stack traceback:
Apr 06 21:09:16 lmp /usr/lib/gdm-x-session[39825]:         [C]: in function 'string.gsub'
Apr 06 21:09:16 lmp /usr/lib/gdm-x-session[39825]:         /home/hk/.config/awesome/widget/weather/init.lua:258: in function </home/hk/.config/awesome/widget/weather/init.lua:238>
Apr 06 21:09:16 lmp /usr/lib/gdm-x-session[39825]:         (...tail calls...)
Apr 06 21:09:16 lmp /usr/lib/gdm-x-session[39825]:         /usr/share/awesome/lib/awful/spawn.lua:487: in function </usr/share/awesome/lib/awful/spawn.lua:481>
Apr 06 21:09:16 lmp /usr/lib/gdm-x-session[39825]:         [C]: in function 'xpcall'
Apr 06 21:09:16 lmp /usr/lib/gdm-x-session[39825]:         /usr/share/awesome/lib/gears/protected_call.lua:36: in function </usr/share/awesome/lib/gears/protected_call.lua:35>
Apr 06 21:09:16 lmp /usr/lib/gdm-x-session[39825]:         (...tail calls...)
Apr 06 21:09:16 lmp /usr/lib/gdm-x-session[39825]:         /usr/share/awesome/lib/awful/spawn.lua:586: in upvalue 'done'
Apr 06 21:09:16 lmp /usr/lib/gdm-x-session[39825]:         /usr/share/awesome/lib/awful/spawn.lua:601: in function </usr/share/awesome/lib/awful/spawn.lua:593>
Apr 06 21:09:16 lmp /usr/lib/gdm-x-session[41321]: acpi_listen: can't open socket /var/run/acpid.socket: No such file or directory
Apr 06 21:09:16 lmp /usr/lib/gdm-x-session[39825]: 2020-04-06 21:09:16 E: awesome: Error during a protected call: attempt to compare number with nil
Apr 06 21:09:16 lmp /usr/lib/gdm-x-session[39825]: stack traceback:
Apr 06 21:09:16 lmp /usr/lib/gdm-x-session[39825]:         [C]: in function 'math.min'
Apr 06 21:09:16 lmp /usr/lib/gdm-x-session[39825]:         /usr/share/awesome/lib/wibox/widget/slider.lua:344: in function 'wibox.widget.slider.set_value'
Apr 06 21:09:16 lmp /usr/lib/gdm-x-session[39825]:         /home/hk/.config/awesome/widget/music/mpd-music-updater.lua:299: in function </home/hk/.config/awesome/widget/music/mpd-music-updater.lua:292>
Apr 06 21:09:16 lmp /usr/lib/gdm-x-session[39825]:         (...tail calls...)
Apr 06 21:09:16 lmp /usr/lib/gdm-x-session[39825]:         /usr/share/awesome/lib/awful/spawn.lua:487: in function </usr/share/awesome/lib/awful/spawn.lua:481>
Apr 06 21:09:16 lmp /usr/lib/gdm-x-session[39825]:         [C]: in function 'xpcall'
Apr 06 21:09:16 lmp /usr/lib/gdm-x-session[39825]:         /usr/share/awesome/lib/gears/protected_call.lua:36: in function </usr/share/awesome/lib/gears/protected_call.lua:35>
Apr 06 21:09:16 lmp /usr/lib/gdm-x-session[39825]:         (...tail calls...)
Apr 06 21:09:16 lmp /usr/lib/gdm-x-session[39825]:         /usr/share/awesome/lib/awful/spawn.lua:586: in upvalue 'done'
Apr 06 21:09:16 lmp /usr/lib/gdm-x-session[39825]:         /usr/share/awesome/lib/awful/spawn.lua:601: in function </usr/share/awesome/lib/awful/spawn.lua:593>
Apr 06 21:09:17 lmp /usr/lib/gdm-x-session[41381]: MPD error: Connection refused
Apr 06 21:09:17 lmp /usr/lib/gdm-x-session[39825]: 2020-04-06 21:09:17 E: awesome: Error during a protected call: attempt to compare number with nil
Apr 06 21:09:17 lmp /usr/lib/gdm-x-session[39825]: stack traceback:
Apr 06 21:09:17 lmp /usr/lib/gdm-x-session[39825]:         [C]: in function 'math.min'
Apr 06 21:09:17 lmp /usr/lib/gdm-x-session[39825]:         /usr/share/awesome/lib/wibox/widget/slider.lua:344: in function 'wibox.widget.slider.set_value'
Apr 06 21:09:17 lmp /usr/lib/gdm-x-session[39825]:         /home/hk/.config/awesome/widget/music/mpd-music-updater.lua:299: in function </home/hk/.config/awesome/widget/music/mpd-music-updater.lua:292>
Apr 06 21:09:17 lmp /usr/lib/gdm-x-session[39825]:         (...tail calls...)
Apr 06 21:09:17 lmp /usr/lib/gdm-x-session[39825]:         /usr/share/awesome/lib/awful/spawn.lua:487: in function </usr/share/awesome/lib/awful/spawn.lua:481>
Apr 06 21:09:17 lmp /usr/lib/gdm-x-session[39825]:         [C]: in function 'xpcall'
Apr 06 21:09:17 lmp /usr/lib/gdm-x-session[39825]:         /usr/share/awesome/lib/gears/protected_call.lua:36: in function </usr/share/awesome/lib/gears/protected_call.lua:35>
Apr 06 21:09:17 lmp /usr/lib/gdm-x-session[39825]:         (...tail calls...)
Apr 06 21:09:17 lmp /usr/lib/gdm-x-session[39825]:         /usr/share/awesome/lib/awful/spawn.lua:586: in upvalue 'done'
Apr 06 21:09:17 lmp /usr/lib/gdm-x-session[39825]:         /usr/share/awesome/lib/awful/spawn.lua:601: in function </usr/share/awesome/lib/awful/spawn.lua:593>
```

**Comment by Hkyx** [comment] 2020-04-07 01:28
removed the acpid problem creating the folder it need, but still got theses errors: 

```
Apr 06 21:25:33 lmp /usr/lib/gdm-x-session[39825]: 2020-04-06 21:25:33 E: awesome: Error during a protected call: attempt to compare number with nil
Apr 06 21:25:33 lmp /usr/lib/gdm-x-session[39825]: stack traceback:
Apr 06 21:25:33 lmp /usr/lib/gdm-x-session[39825]:         [C]: in function 'math.min'
Apr 06 21:25:33 lmp /usr/lib/gdm-x-session[39825]:         /usr/share/awesome/lib/wibox/widget/slider.lua:344: in function 'wibox.widget.slider.set_value'
Apr 06 21:25:33 lmp /usr/lib/gdm-x-session[39825]:         /home/hk/.config/awesome/widget/music/mpd-music-updater.lua:299: in function </home/hk/.config/awesome/widget/music/mpd-music-updater.lua:292>
Apr 06 21:25:33 lmp /usr/lib/gdm-x-session[39825]:         (...tail calls...)
Apr 06 21:25:33 lmp /usr/lib/gdm-x-session[39825]:         /usr/share/awesome/lib/awful/spawn.lua:487: in function </usr/share/awesome/lib/awful/spawn.lua:481>
Apr 06 21:25:33 lmp /usr/lib/gdm-x-session[39825]:         [C]: in function 'xpcall'
Apr 06 21:25:33 lmp /usr/lib/gdm-x-session[39825]:         /usr/share/awesome/lib/gears/protected_call.lua:36: in function </usr/share/awesome/lib/gears/protected_call.lua:35>
Apr 06 21:25:33 lmp /usr/lib/gdm-x-session[39825]:         (...tail calls...)
Apr 06 21:25:33 lmp /usr/lib/gdm-x-session[39825]:         /usr/share/awesome/lib/awful/spawn.lua:586: in upvalue 'done'
Apr 06 21:25:33 lmp /usr/lib/gdm-x-session[39825]:         /usr/share/awesome/lib/awful/spawn.lua:601: in function </usr/share/awesome/lib/awful/spawn.lua:593>
 π ~ ❯ 
```

**Comment by Hkyx** [comment] 2020-04-07 02:10
the problem seems related to linead theme, if I use floppy, all is good.

**Comment by manilarome** [comment] 2020-04-07 02:22
Can you change this [line](https://github.com/manilarome/the-glorious-dotfiles/blob/d56dd2dc2615c57e799a93e95b27b63a1669d2ed/config/awesome/linear/layout/bottom-panel.lua#L17) to `local panel_y = s.geometry.y + (s.geometry.height - panel_height)
`? I can't reproduce your problem, it works fine here . Anyway, we're using `wibox` for the bottom panel not `wibar`.

![image](https://user-images.githubusercontent.com/40349590/78623061-5e06ac80-78b9-11ea-94c9-2e4f4efc90d9.png)

**Comment by manilarome** [comment] 2020-04-07 02:27
What is your screen resolution? Can you try reloading awesomewm?

**Comment by manilarome** [comment] 2020-04-08 13:09
Hey, I'll just assume that you already fixed it. I'm probably wrong tho, so please, just reopen this again if I'm mistaken. :) Good day sir.

**Comment by Hkyx** [comment] 2020-04-08 13:17
Hi @manilarome 

it seems my last update don't appear, I tried the fix and multiple resolution from 1920 to 2560px but it does not change the problem

ty for the following :)

**Comment by manilarome** [comment] 2020-04-08 13:24
Oof sorry if I closed this.

Can please try changing [lines](https://github.com/manilarome/the-glorious-dotfiles/blob/657d497517eb1b3f8ff90bbb2e6d63393f8ae443/config/awesome/linear/layout/bottom-panel.lua#L17-L31) to this. I just change the bottom-panel from wibox to awful.wibar.

```lua
	local panel_y = s.geometry.y

	local panel = awful.wibar
	{
		ontop = true,
		screen = s,
		type = 'dock',
		height = panel_height,
		width = s.geometry.width,
		x = s.geometry.x,
		y = dpi(panel_y),
		position = 'bottom',
		bg = beautiful.background,
		fg = beautiful.fg_normal
	}
```

**Comment by Hkyx** [comment] 2020-04-08 13:34
And it worked ! :) Ty @manilarome  :)

**Comment by manilarome** [comment] 2020-04-08 13:38
Nice! Thanks for reporting this! I'm closing this now :)

**Closed by manilarome** 2020-04-08 13:38 UTC
Labels: bug
