### ISSUE TITLE
[BUG?][Surreal] lockscreen modul blocks startup

### ISSUE THREAD

**Issue by NeoScaler** [manilarome/the-glorious-dotfiles#156] opened 2020-07-15 08:39 UTC
Hi there,

I am having problems getting the Surreal setup to work. It starts, but no keys are working. Following is the output:

```
WARNING: modelines must use ASCII
2020-07-15 10:31:36 W: awesome: luaA_dofunction:78: error while running function!
stack traceback:
	/usr/local/share/awesome/lib/awful/screen.lua:344: in function 'awful.screen.preferred'
	/home/julian/.config/awesome/module/notifications.lua:155: in local 'func'
	/usr/local/share/awesome/lib/gears/object.lua:190: in function 'naughty.core.emit_signal'
	/usr/local/share/awesome/lib/naughty/notification.lua:1204: in function </usr/local/share/awesome/lib/naughty/notification.lua:1109>
	(...tail calls...)
	/home/julian/.config/awesome/module/notifications.lua:89: in local 'func'
	/usr/local/share/awesome/lib/gears/object.lua:190: in function 'naughty.core.emit_signal'
	/usr/local/share/awesome/lib/naughty/init.lua:83: in function </usr/local/share/awesome/lib/naughty/init.lua:75>
	[C]: in ?
	[C]: in ?
	[C]: in function 'require'
	/home/julian/.config/awesome/module/lockscreen.lua:13: in main chunk
	[C]: in function 'require'
	/home/julian/.config/awesome/rc.lua:45: in main chunk
error: /usr/local/share/awesome/lib/awful/screen.lua:344: attempt to index a nil value (local 'c')
error while running function!
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	/home/julian/.config/awesome/module/lockscreen.lua:13: in main chunk
	[C]: in function 'require'
	/home/julian/.config/awesome/rc.lua:45: in main chunk
error: error loading module 'liblua_pam' from file '/home/julian/.config/awesome//library/liblua_pam.so':
	liblua.so.5.3: cannot open shared object file: No such file or directory
error while running function!
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	/home/julian/.config/awesome/module/lockscreen.lua:13: in main chunk
	[C]: in function 'require'
	/home/julian/.config/awesome/rc.lua:45: in main chunk
error: error loading module 'liblua_pam' from file '/home/julian/.config/awesome//library/liblua_pam.so':
	liblua.so.5.3: cannot open shared object file: No such file or directory
2020-07-15 10:31:36 W: awesome: a_glib_poll:470: Last main loop iteration took 0.531913 seconds! Increasing limit for this warning to that value.
Simple mixer control 'Master',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 65536
  Mono:
  Front Left: Playback 65536 [100%] [on]
  Front Right: Playback 65536 [100%] [on]
Simple mixer control 'Master',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 65536
  Mono:
  Front Left: Playback 65536 [100%] [on]
  Front Right: Playback 65536 [100%] [on]
MPD error: Connection refused
2020-07-15 10:31:37 E: awesome: Error on line 26: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp;
```

My awesome -v:
```
awesome v4.3-858-g49a3859c (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

Any ideas?
`

**Comment by manilarome** [comment] 2020-07-15 08:43
> liblua.so.5.3: cannot open shared object file: No such file or directory

You need lua5.3

**Comment by manilarome** [comment] 2020-07-15 08:46
Yep I should write the lua version needed. Or support other versions of lua for the lua-pam library.

**Comment by NeoScaler** [comment] 2020-07-15 08:51
> > liblua.so.5.3: cannot open shared object file: No such file or directory
> 
> You need lua5.3

But I have LUA 5.3: 

```
awesome v4.3-858-g49a3859c (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
```

**Comment by manilarome** [comment] 2020-07-15 09:01
> But I have LUA 5.3:

Oof, I'm sorry. Please try to compile/build [this](https://github.com/RMTT/lua-pam) then replace `awesome/library/liblua_pam.so` with it. I really don't know what is the problem here aside from "missing" `liblua.so.5.3`. You are on 64-bit system right?

**Comment by manilarome** [comment] 2020-07-15 09:03
Right now, based on your log, the problem is in the lockscreen module. You can temporarily disable it in the `rc.lua.`

**Comment by NeoScaler** [comment] 2020-07-15 10:36
> Right now, based on your log, the problem is in the lockscreen module. You can temporarily disable it in the `rc.lua.`

First, thanks a lot for your work and support here! Without the lockscreen module it works fine. Recompiling the library unfortunately does not work:

```
Scanning dependencies of target lua_pam
[ 50%] Building CXX object CMakeFiles/lua_pam.dir/src/main.cpp.o
[100%] Linking CXX shared library liblua_pam.so
/usr/bin/ld: /usr/local/lib/liblua.a(lstate.o): relocation R_X86_64_PC32 against symbol `lua_newstate' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/lua_pam.dir/build.make:84: liblua_pam.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/lua_pam.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```
And yes, I am running a 64bit system.

**Comment by manilarome** [comment] 2020-07-15 12:11
Weird. I compiled it successfully.

![image](https://user-images.githubusercontent.com/40349590/87543363-33599a80-c6d7-11ea-9476-bbbee4f5b60c.png)

Maybe you're missing a dependency or something. Hey @RMTT can you please help me with this? Is there a required dependency/ies for the [lua-pam](https://github.com/rmtt/lua-pam)?

**Comment by RMTT** [comment] 2020-07-15 12:27
@manilarome I have nerver suffered this error,seems a machine related issue.
@NeoScaler  try this solution:
add following two lines in CMakeLists.txt after `set(CMAKE_CXX_STANDARD 14)`:
```cpp
set( CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -fPIC" )
set( CMAKE_C_FLAGS  "${CMAKE_C_FLAGS} -fPIC" )
```
and then rebuild it.

**Comment by manilarome** [comment] 2020-07-15 12:49
Thank you @RMTT !

**Comment by NeoScaler** [comment] 2020-07-15 13:36
> @manilarome I have nerver suffered this error,seems a machine related issue.
> @NeoScaler try this solution:
> add following two lines in CMakeLists.txt after `set(CMAKE_CXX_STANDARD 14)`:
> 
> ```c++
> set( CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -fPIC" )
> set( CMAKE_C_FLAGS  "${CMAKE_C_FLAGS} -fPIC" )
> ```
> 
> and then rebuild it.

Thanks for the help, but this does not change anything. I deleted the build folder, changed the txt and tried the build again.

```cmake_minimum_required(VERSION 3.15)
project(lua_pam)

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -fPIC")
set(CMAKE_C_FLAGS  "${CMAKE_C_FLAGS} -fPIC")

set(SOURCE_DIR src)

add_library(lua_pam SHARED ${SOURCE_DIR}/main.cpp)
target_link_libraries(lua_pam lua pam)
```

**Comment by manilarome** [comment] 2020-07-15 13:46
> does not change anything.

Then, I really don't have an idea how to fix this. Anyway I noticed that you're on `lua 5.3.3`, please try to update it to `5.3.5`. If this doesn't fix it, I'm sorry.

**Comment by NeoScaler** [comment] 2020-07-15 15:23
5.3.5 is not available for my distro, perhaps I am building it from source.

Could be that I have a static compiled LUA library installed and that is the problem, at least that is what I found here: https://superuser.com/a/557901/141056

**Comment by manilarome** [comment] 2020-07-15 23:39
> Could be that I have a static compiled LUA library installed and that is the problem

Hmm I think so hence the ```/usr/bin/ld: /usr/local/lib/liblua.a(lstate.o): relocation R_X86_64_PC32 against symbol `lua_newstate' can not be used when making a shared object; recompile with -fPIC``` error.

**Comment by RMTT** [comment] 2020-07-16 00:23
> 5.3.5 is not available for my distro, perhaps I am building it from source.
> 
> Could be that I have a static compiled LUA library installed and that is the problem, at least that is what I found here: https://superuser.com/a/557901/141056

i think so, can you find liblua.so in your machine?

**Comment by manilarome** [comment] 2020-07-21 01:31
So I installed ubuntu and I also reproduced this. It seems that ubuntu is not linking the shared libraries so the lua-pam library can't find the `liblua.so.5.3` (located in `/usr/include/lua/something`). I tried running `ldconfig` but it doesn't fix the problem. Sadly, I don't have an idea how to fix this. Patches welcome!

**Comment by manilarome** [comment] 2020-07-21 02:48
So in Ubuntu, the `lua.hpp` is located in `/usr/include/lua5.3/`, but the `lua-pam` library is only reading the libraries in `/usr/include/`. So moving/copying/symlinking the contents of `/usr/include/lua5.3/` to `/usr/include/` fix the missing `liblua.so.5.3`. While I can't find both `pam_appl.h`, and `pam_misc.h` in the `/usr/include/security/`. @RMTT  what's your say about this?

**Comment by RMTT** [comment] 2020-07-21 02:55
Hey,i tried on ubuntu 18.04 server,and it's ok.


> While I can't find both `pam_appl.h`, and `pam_misc.h` in the `/usr/include/security/`

I also faced this issue,just install the `libpam0g-dev`,from https://packages.debian.org/cgi-bin/search_contents.pl?word=pam_appl.h&amp;searchmode=searchfiles&amp;case=insensitive&amp;version=stable&amp;arch=i386

**Comment by RMTT** [comment] 2020-07-21 02:58
Those issue seems caused by that the ubuntu cannot create some soft links by default.

**Comment by manilarome** [comment] 2020-07-21 03:56
> Hey,i tried on ubuntu 18.04 server,and it's ok.
> 
> 
> > While I can't find both `pam_appl.h`, and `pam_misc.h` in the `/usr/include/security/`
> 
> I also faced this issue,just install the `libpam0g-dev`

I see. Thanks! Fixed the missing pam libs.


> Those issue seems caused by that the ubuntu cannot create some soft links by default.

So the user have to manually link them to fix it, right? Maybe I should write it in the wiki.

**Comment by RMTT** [comment] 2020-07-21 06:21
> So the user have to manually link them to fix it, right? Maybe I should write it in the wiki.

yeah,i will add some description to the lua-pam project later : )

**Comment by manilarome** [comment] 2020-07-21 06:53
Thanks @RMTT! So I managed to fix the `lockscreen` module by creating symlinks:

```bash
cd /usr/lib/x86_64-linux-gnu/
sudo ln -s liblua5.3.so.0.0.0 /usr/lib/x86_64-linux-gnu/liblua5.3.so

cd /usr/include/lua5.3/
sudo ln -s lauxlib.h /usr/include/lauxlib.h
sudo ln -s luaconf.h /usr/include/luaconf.h
sudo ln -s lua.h /usr/include/lua.h
sudo ln -s lualib.h /usr/include/lualib.h
sudo ln -s lua.hpp /usr/include/lua.hpp
```

Is there a better way to do this? It's just Arch and Ubuntu have a different path for lua libs. Will test on Debian later if it has the same problem.

**Comment by RMTT** [comment] 2020-07-21 07:41
> Thanks @RMTT! So I managed to fix the `lockscreen` module by creating symlinks:
> 
> ```shell
> cd /usr/lib/x86_64-linux-gnu/
> sudo ln -s liblua5.3.so.0.0.0 /usr/lib/x86_64-linux-gnu/liblua5.3.so
> 
> cd /usr/include/lua5.3/
> sudo ln -s lauxlib.h /usr/include/lauxlib.h
> sudo ln -s luaconf.h /usr/include/luaconf.h
> sudo ln -s lua.h /usr/include/lua.h
> sudo ln -s lualib.h /usr/include/lualib.h
> sudo ln -s lua.hpp /usr/include/lua.hpp
> ```
> 
> Is there a better way to do this? It's just Arch and Ubuntu have a different path for lua libs. Will test on Debian later if it has the same problem.

On my ubuntu 18.04 server,just need `sudo ln -s lua.hpp /usr/include/lua.hpp` and install `libpam0g-dev` and 'liblua-dev'.
I'm not sure for other headers on other debian/ubuntu version : )

**Comment by manilarome** [comment] 2020-07-21 08:47
> On my ubuntu 18.04 server,just need sudo ln -s lua.hpp /usr/include/lua.hpp and install libpam0g-dev and 'liblua-dev'.

I see! Thought I need all the other one just to be safe lol.

>  I'm not sure for other headers on other debian/ubuntu version : )

Yeah, I will test it later or tomorrow. I'm currently downloading a Debian iso.

**Comment by manilarome** [comment] 2020-07-21 13:05
>  I'm not sure for other headers on other debian/ubuntu version : )

Confirmed. Same as ubuntu. It looks like debian-based distros put the lua header to `/usr/include/lua5.3/`. While on Arch it's just `/usr/include/`.

**Comment by manilarome** [comment] 2020-07-21 23:21
Hello @NeoScaler, this can be solved by creating a symlink of `/usr/include/lua5.3/lua.hpp` to `/usr/include/lua.hpp` and by installing `libpam0g-dev`. Closing this now. Will just pin this issue. Thanks!

```bash
# ln -s /usr/include/lua5.3/lua.hpp /usr/include/lua.hpp
# apt install libpam0g-dev
```

**Closed by manilarome** 2020-07-21 23:21 UTC
Labels: bug, dependency, discussion
